# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Install.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rInstall.proto\"\x1d\n\x0eInstallRequest\x12\x0b\n\x03\x65lf\x18\x01 \x02(\x0c\"\x0e\n\x0cInstallReply')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Install_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INSTALLREQUEST._serialized_start=17
  _INSTALLREQUEST._serialized_end=46
  _INSTALLREPLY._serialized_start=48
  _INSTALLREPLY._serialized_end=62
# @@protoc_insertion_point(module_scope)
