# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Table.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bTable.proto\"\x13\n\x11TablesListRequest\"4\n\x0fTablesListReply\x12!\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x10.TableDefinition\"\xbe\x01\n\x0fTableDefinition\x12\x12\n\ntable_name\x18\x01 \x02(\t\x12.\n\ntable_type\x18\x02 \x02(\x0e\x32\x1a.TableDefinition.TableType\x12\x10\n\x08key_size\x18\x03 \x02(\r\x12\x12\n\nvalue_size\x18\x04 \x02(\r\x12\x13\n\x0bmax_entries\x18\x05 \x02(\r\",\n\tTableType\x12\n\n\x06UNSPEC\x10\x00\x12\x08\n\x04HASH\x10\x01\x12\t\n\x05\x41RRAY\x10\x02\"&\n\x10TableListRequest\x12\x12\n\ntable_name\x18\x01 \x02(\t\"o\n\x0eTableListReply\x12\x1c\n\x06status\x18\x01 \x02(\x0e\x32\x0c.TableStatus\x12\x1f\n\x05\x65ntry\x18\x02 \x01(\x0b\x32\x10.TableDefinition\x12\x0f\n\x07n_items\x18\x03 \x01(\r\x12\r\n\x05items\x18\x04 \x01(\x0c\"7\n\x14TableEntryGetRequest\x12\x12\n\ntable_name\x18\x01 \x02(\t\x12\x0b\n\x03key\x18\x02 \x02(\x0c\"N\n\x12TableEntryGetReply\x12\x1c\n\x06status\x18\x01 \x02(\x0e\x32\x0c.TableStatus\x12\x0b\n\x03key\x18\x02 \x01(\x0c\x12\r\n\x05value\x18\x03 \x01(\x0c\"I\n\x17TableEntryInsertRequest\x12\x12\n\ntable_name\x18\x01 \x02(\t\x12\x0b\n\x03key\x18\x02 \x02(\x0c\x12\r\n\x05value\x18\x03 \x02(\x0c\"5\n\x15TableEntryInsertReply\x12\x1c\n\x06status\x18\x01 \x02(\x0e\x32\x0c.TableStatus\":\n\x17TableEntryDeleteRequest\x12\x12\n\ntable_name\x18\x01 \x02(\t\x12\x0b\n\x03key\x18\x02 \x02(\x0c\"5\n\x15TableEntryDeleteReply\x12\x1c\n\x06status\x18\x01 \x02(\x0e\x32\x0c.TableStatus*D\n\x0bTableStatus\x12\x0b\n\x07SUCCESS\x10\x00\x12\x13\n\x0fTABLE_NOT_FOUND\x10\x01\x12\x13\n\x0f\x45NTRY_NOT_FOUND\x10\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Table_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TABLESTATUS._serialized_start=818
  _TABLESTATUS._serialized_end=886
  _TABLESLISTREQUEST._serialized_start=15
  _TABLESLISTREQUEST._serialized_end=34
  _TABLESLISTREPLY._serialized_start=36
  _TABLESLISTREPLY._serialized_end=88
  _TABLEDEFINITION._serialized_start=91
  _TABLEDEFINITION._serialized_end=281
  _TABLEDEFINITION_TABLETYPE._serialized_start=237
  _TABLEDEFINITION_TABLETYPE._serialized_end=281
  _TABLELISTREQUEST._serialized_start=283
  _TABLELISTREQUEST._serialized_end=321
  _TABLELISTREPLY._serialized_start=323
  _TABLELISTREPLY._serialized_end=434
  _TABLEENTRYGETREQUEST._serialized_start=436
  _TABLEENTRYGETREQUEST._serialized_end=491
  _TABLEENTRYGETREPLY._serialized_start=493
  _TABLEENTRYGETREPLY._serialized_end=571
  _TABLEENTRYINSERTREQUEST._serialized_start=573
  _TABLEENTRYINSERTREQUEST._serialized_end=646
  _TABLEENTRYINSERTREPLY._serialized_start=648
  _TABLEENTRYINSERTREPLY._serialized_end=701
  _TABLEENTRYDELETEREQUEST._serialized_start=703
  _TABLEENTRYDELETEREQUEST._serialized_end=761
  _TABLEENTRYDELETEREPLY._serialized_start=763
  _TABLEENTRYDELETEREPLY._serialized_end=816
# @@protoc_insertion_point(module_scope)
