/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Header.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Header.pb-c.h"
void   header__init
                     (Header         *message)
{
  static const Header init_value = HEADER__INIT;
  *message = init_value;
}
size_t header__get_packed_size
                     (const Header *message)
{
  assert(message->base.descriptor == &header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t header__pack
                     (const Header *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t header__pack_to_buffer
                     (const Header *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Header *
       header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Header *)
     protobuf_c_message_unpack (&header__descriptor,
                                allocator, len, data);
}
void   header__free_unpacked
                     (Header *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue header__type__enum_values_by_number[16] =
{
  { "HELLO", "HEADER__TYPE__HELLO", 0 },
  { "INSTALL_REQUEST", "HEADER__TYPE__INSTALL_REQUEST", 1 },
  { "INSTALL_REPLY", "HEADER__TYPE__INSTALL_REPLY", 2 },
  { "TABLES_LIST_REQUEST", "HEADER__TYPE__TABLES_LIST_REQUEST", 3 },
  { "TABLES_LIST_REPLY", "HEADER__TYPE__TABLES_LIST_REPLY", 4 },
  { "TABLE_LIST_REQUEST", "HEADER__TYPE__TABLE_LIST_REQUEST", 5 },
  { "TABLE_LIST_REPLY", "HEADER__TYPE__TABLE_LIST_REPLY", 6 },
  { "TABLE_ENTRY_GET_REQUEST", "HEADER__TYPE__TABLE_ENTRY_GET_REQUEST", 7 },
  { "TABLE_ENTRY_GET_REPLY", "HEADER__TYPE__TABLE_ENTRY_GET_REPLY", 8 },
  { "TABLE_ENTRY_INSERT_REQUEST", "HEADER__TYPE__TABLE_ENTRY_INSERT_REQUEST", 9 },
  { "TABLE_ENTRY_INSERT_REPLY", "HEADER__TYPE__TABLE_ENTRY_INSERT_REPLY", 10 },
  { "TABLE_ENTRY_DELETE_REQUEST", "HEADER__TYPE__TABLE_ENTRY_DELETE_REQUEST", 11 },
  { "TABLE_ENTRY_DELETE_REPLY", "HEADER__TYPE__TABLE_ENTRY_DELETE_REPLY", 12 },
  { "PACKET_IN", "HEADER__TYPE__PACKET_IN", 13 },
  { "PACKET_OUT", "HEADER__TYPE__PACKET_OUT", 14 },
  { "NOTIFY", "HEADER__TYPE__NOTIFY", 15 },
};
static const ProtobufCIntRange header__type__value_ranges[] = {
{0, 0},{0, 16}
};
static const ProtobufCEnumValueIndex header__type__enum_values_by_name[16] =
{
  { "HELLO", 0 },
  { "INSTALL_REPLY", 2 },
  { "INSTALL_REQUEST", 1 },
  { "NOTIFY", 15 },
  { "PACKET_IN", 13 },
  { "PACKET_OUT", 14 },
  { "TABLES_LIST_REPLY", 4 },
  { "TABLES_LIST_REQUEST", 3 },
  { "TABLE_ENTRY_DELETE_REPLY", 12 },
  { "TABLE_ENTRY_DELETE_REQUEST", 11 },
  { "TABLE_ENTRY_GET_REPLY", 8 },
  { "TABLE_ENTRY_GET_REQUEST", 7 },
  { "TABLE_ENTRY_INSERT_REPLY", 10 },
  { "TABLE_ENTRY_INSERT_REQUEST", 9 },
  { "TABLE_LIST_REPLY", 6 },
  { "TABLE_LIST_REQUEST", 5 },
};
const ProtobufCEnumDescriptor header__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Header.Type",
  "Type",
  "Header__Type",
  "",
  16,
  header__type__enum_values_by_number,
  16,
  header__type__enum_values_by_name,
  1,
  header__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor header__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Header, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Header, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned header__field_indices_by_name[] = {
  1,   /* field[1] = length */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Header",
  "Header",
  "Header",
  "",
  sizeof(Header),
  2,
  header__field_descriptors,
  header__field_indices_by_name,
  1,  header__number_ranges,
  (ProtobufCMessageInit) header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
