/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Install.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Install.pb-c.h"
void   install_request__init
                     (InstallRequest         *message)
{
  static const InstallRequest init_value = INSTALL_REQUEST__INIT;
  *message = init_value;
}
size_t install_request__get_packed_size
                     (const InstallRequest *message)
{
  assert(message->base.descriptor == &install_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t install_request__pack
                     (const InstallRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &install_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t install_request__pack_to_buffer
                     (const InstallRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &install_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
InstallRequest *
       install_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (InstallRequest *)
     protobuf_c_message_unpack (&install_request__descriptor,
                                allocator, len, data);
}
void   install_request__free_unpacked
                     (InstallRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &install_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   install_reply__init
                     (InstallReply         *message)
{
  static const InstallReply init_value = INSTALL_REPLY__INIT;
  *message = init_value;
}
size_t install_reply__get_packed_size
                     (const InstallReply *message)
{
  assert(message->base.descriptor == &install_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t install_reply__pack
                     (const InstallReply *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &install_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t install_reply__pack_to_buffer
                     (const InstallReply *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &install_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
InstallReply *
       install_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (InstallReply *)
     protobuf_c_message_unpack (&install_reply__descriptor,
                                allocator, len, data);
}
void   install_reply__free_unpacked
                     (InstallReply *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &install_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor install_request__field_descriptors[1] =
{
  {
    "elf",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(InstallRequest, elf),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned install_request__field_indices_by_name[] = {
  0,   /* field[0] = elf */
};
static const ProtobufCIntRange install_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor install_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "InstallRequest",
  "InstallRequest",
  "InstallRequest",
  "",
  sizeof(InstallRequest),
  1,
  install_request__field_descriptors,
  install_request__field_indices_by_name,
  1,  install_request__number_ranges,
  (ProtobufCMessageInit) install_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define install_reply__field_descriptors NULL
#define install_reply__field_indices_by_name NULL
#define install_reply__number_ranges NULL
const ProtobufCMessageDescriptor install_reply__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "InstallReply",
  "InstallReply",
  "InstallReply",
  "",
  sizeof(InstallReply),
  0,
  install_reply__field_descriptors,
  install_reply__field_indices_by_name,
  0,  install_reply__number_ranges,
  (ProtobufCMessageInit) install_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
